#!/usr/bin/env fish

# Emergency mapping in case something broke
riverctl map normal Super+Shift E exit

set DIR (dirname (status -f))

# Keybinds
fish $DIR/config.fish

# App daemons
fish $DIR/env.fish
