pragma Singleton

import QtQuick

QtObject {
    // Tokyonight Night
    // property color bg: "#1a1b26"
    // property color bg_dark: "#16161e"
    // property color bg_dark1: "#0C0E14"
    // property color bg_highlight: "#292e42"
    // property color blue: "#7aa2f7"
    // property color blue0: "#3d59a1"
    // property color blue1: "#2ac3de"
    // property color blue2: "#0db9d7"
    // property color blue5: "#89ddff"
    // property color blue6: "#b4f9f8"
    // property color blue7: "#394b70"
    // property color comment: "#565f89"
    // property color cyan: "#7dcfff"
    // property color dark3: "#545c7e"
    // property color dark5: "#737aa2"
    // property color fg: "#c0caf5"
    // property color fg_dark: "#a9b1d6"
    // property color fg_gutter: "#3b4261"
    // property color green: "#9ece6a"
    // property color green1: "#73daca"
    // property color green2: "#41a6b5"
    // property color magenta: "#bb9af7"
    // property color magenta2: "#ff007c"
    // property color orange: "#ff9e64"
    // property color purple: "#9d7cd8"
    // property color red: "#f7768e"
    // property color red1: "#db4b4b"
    // property color teal: "#1abc9c"
    // property color terminal_black: "#414868"
    // property color yellow: "#e0af68"
    // property color gitAdd: "#449dab"
    // property color gitChange: "#6183bb"
    // property color gitDelete: "#914c54"

    property QtObject dark_medium: QtObject {
        // Palette 1 (background colors)
        property color bg_dim: "#232A2E"
        property color bg0: "#2D353B"
        property color bg1: "#343F44"
        property color bg2: "#3D484D"
        property color bg3: "#475258"
        property color bg4: "#4F585E"
        property color bg5: "#56635F"
        property color bg_visual: "#543A48"
        property color bg_red: "#514045"
        property color bg_yellow: "#4D4C43"
        property color bg_green: "#425047"
        property color bg_blue: "#3A515D"
        property color bg_purple: "#4A444E"

        // Palette 2 (foreground colors)
        property color fg: "#D3C6AA"
        property color red: "#E67E80"
        property color orange: "#E69875"
        property color yellow: "#DBBC7F"
        property color green: "#A7C080"
        property color aqua: "#83C092"
        property color blue: "#7FBBB3"
        property color purple: "#D699B6"
        property color grey0: "#7A8478"
        property color grey1: "#859289"
        property color grey2: "#9DA9A0"
        property color statusline1: green
        property color statusline2: fg
        property color statusline3: red
    }
    property QtObject matugen: QtObject {
        property QtObject colors: QtObject {
            property QtObject dark: QtObject {
                property color background: "#11140f"
                property color error: "#ffb4ab"
                property color error_container: "#93000a"
                property color inverse_on_surface: "#2e322b"
                property color inverse_primary: "#416835"
                property color inverse_surface: "#e1e4da"
                property color on_background: "#e1e4da"
                property color on_error: "#690005"
                property color on_error_container: "#ffdad6"
                property color on_primary: "#13380a"
                property color on_primary_container: "#c1efaf"
                property color on_primary_fixed: "#022100"
                property color on_primary_fixed_variant: "#2a4f1f"
                property color on_secondary: "#273421"
                property color on_secondary_container: "#d7e8cc"
                property color on_secondary_fixed: "#121f0e"
                property color on_secondary_fixed_variant: "#3d4b37"
                property color on_surface: "#e1e4da"
                property color on_surface_variant: "#c3c8bc"
                property color on_tertiary: "#003739"
                property color on_tertiary_container: "#bcebee"
                property color on_tertiary_fixed: "#002021"
                property color on_tertiary_fixed_variant: "#1e4e50"
                property color outline: "#8d9387"
                property color outline_variant: "#43483f"
                property color primary: "#a6d394"
                property color primary_container: "#2a4f1f"
                property color primary_fixed: "#c1efaf"
                property color primary_fixed_dim: "#a6d394"
                property color scrim: "#000000"
                property color secondary: "#bbcbb1"
                property color secondary_container: "#3d4b37"
                property color secondary_fixed: "#d7e8cc"
                property color secondary_fixed_dim: "#bbcbb1"
                property color shadow: "#000000"
                property color surface: "#11140f"
                property color surface_bright: "#373a34"
                property color surface_container: "#1d211b"
                property color surface_container_high: "#272b25"
                property color surface_container_highest: "#32362f"
                property color surface_container_low: "#191d17"
                property color surface_container_lowest: "#0c0f0a"
                property color surface_dim: "#11140f"
                property color surface_tint: "#a6d394"
                property color surface_variant: "#43483f"
                property color tertiary: "#a0cfd1"
                property color tertiary_container: "#1e4e50"
                property color tertiary_fixed: "#bcebee"
                property color tertiary_fixed_dim: "#a0cfd1"
            }
            property QtObject light: QtObject {
                property color background: "#f8fbf0"
                property color error: "#ba1a1a"
                property color error_container: "#ffdad6"
                property color inverse_on_surface: "#eff2e8"
                property color inverse_primary: "#a6d394"
                property color inverse_surface: "#2e322b"
                property color on_background: "#191d17"
                property color on_error: "#ffffff"
                property color on_error_container: "#410002"
                property color on_primary: "#ffffff"
                property color on_primary_container: "#022100"
                property color on_primary_fixed: "#022100"
                property color on_primary_fixed_variant: "#2a4f1f"
                property color on_secondary: "#ffffff"
                property color on_secondary_container: "#121f0e"
                property color on_secondary_fixed: "#121f0e"
                property color on_secondary_fixed_variant: "#3d4b37"
                property color on_surface: "#191d17"
                property color on_surface_variant: "#43483f"
                property color on_tertiary: "#ffffff"
                property color on_tertiary_container: "#002021"
                property color on_tertiary_fixed: "#002021"
                property color on_tertiary_fixed_variant: "#1e4e50"
                property color outline: "#73796e"
                property color outline_variant: "#c3c8bc"
                property color primary: "#416835"
                property color primary_container: "#c1efaf"
                property color primary_fixed: "#c1efaf"
                property color primary_fixed_dim: "#a6d394"
                property color scrim: "#000000"
                property color secondary: "#54634d"
                property color secondary_container: "#d7e8cc"
                property color secondary_fixed: "#d7e8cc"
                property color secondary_fixed_dim: "#bbcbb1"
                property color shadow: "#000000"
                property color source_color: "#548c44"
                property color surface: "#f8fbf0"
                property color surface_bright: "#f8fbf0"
                property color surface_container: "#ecefe5"
                property color surface_container_high: "#e6e9df"
                property color surface_container_highest: "#e1e4da"
                property color surface_container_low: "#f2f5eb"
                property color surface_container_lowest: "#ffffff"
                property color surface_dim: "#d8dbd1"
                property color surface_tint: "#416835"
                property color surface_variant: "#dfe4d7"
                property color tertiary: "#386668"
                property color tertiary_container: "#bcebee"
                property color tertiary_fixed: "#bcebee"
                property color tertiary_fixed_dim: "#a0cfd1"
            }
        }
    }
}
